### ISSUE TITLE
Request: Clarify extensibility rules

### ISSUE THREAD

**Issue by bemasc** [tlswg/draft-ietf-tls-ctls#39]
cTLS enumerates keys in the template, but does not explain how templates can be extended.

Suggestion: Clients must reject the whole template if it contains any key they do not understand.  The “optional” key holds a map of optional extensions that are safe to ignore.

**Comment by hannestschofenig** [comment]
Thanks for addressing your own issue with a PR. Creating an IANA registry for the keys used in the configuration data makes sense. 

I would, however, like to point out (and maybe we need to make this explicit) that the configuration information is defined for convenience but is not a mandatory-to-implement functionality for a stack.

**Comment by bemasc** [comment]
Sure, some use cases can pre-arrange, or even hardcode, a specific configuration through a nonstandard channel.  Some use cases (where the client and server are developed separately) obviously cannot.
