### ISSUE TITLE
Request: Make fragmented handshake messages self-delimiting in cTLS/TCP

### ISSUE THREAD

**Issue by bemasc** [tlswg/draft-ietf-tls-ctls#42]
This would allow recipients to detect the end of a handshake message from the CTLSPlaintext header alone, allowing the recipient to reconstruct the entire handshake message before parsing it.  Currently, a streaming parser is required in order to detect the end.

Suggested implementation: Senders set content_type = ctls_handshake_end for a message’s final fragment.

**Comment by ekr** [comment]
I can see why you want that, but it's not generally a TLS property, and I'm reluctant to change things.

**Comment by bemasc** [comment]
AFAIK, TLS does not require a streaming ClientHello parser.  The recipient can read `Handshake.length` (uint24) and then buffer the remainder before parsing.

cTLS, as currently specified, does not have `Handshake.length`.  This means that the recipient has to cross all the way down into the extension parsing code before it finds out that the ClientHello is still incomplete.  Given the complex template-driven handshake parsing code, I think making a streaming parser required is ill-advised.

Given the desire for compactness, I think a flag of some kind on the final handshake message record seems like a reasonable solution, replacing the uint24 length.  It would also simplify Pseudorandom cTLS.  However, if that's not appealing, you could simply reintroduce `Handshake.length`.

**Comment by ekr** [comment]
I could live with this. Objections?

**Comment by bemasc** [comment]
Solved by #59
