### ISSUE TITLE
Request: Make CTLSPlaintext and CTLSCiphertext sizes less variable

### ISSUE THREAD

**Issue by bemasc** [tlswg/draft-ietf-tls-ctls#43]
For cTLS/TCP, the CTLSCiphertext headers could easily all be the same size (1 byte type/flags, 2 byte length).  For cTLS/UDP, the header sizes could be made more predictable.

Suggestions:
* Always suppress sequence numbers and disallow connection IDs in cTLS/TCP, and after the first record in a datagram in cTLS/UDP.
* Move `profile_id` into the cTLS ClientHello struct.

**Comment by hannestschofenig** [comment]
Moving the profile_id into the ClientHello sounds good to me. Here is the PR: https://github.com/tlswg/draft-ietf-tls-ctls/pull/48

**Comment by hannestschofenig** [comment]
Suppressing sequence numbers in cTLS/TCP sounds good to me as well. Here is the PR: https://github.com/tlswg/draft-ietf-tls-ctls/pull/49

**Comment by ekr** [comment]
@bemasc closing as I think we addressed.
