### ISSUE TITLE
What is `profile_id`?

### ISSUE THREAD

**Issue by bemasc** [tlswg/draft-ietf-tls-ctls#54]
The template says it's an integer (in what range?), but the ClientHello says it's 0-255 bytes.

I think it's probably easiest to say it's a string of 0-255 bytes, with the empty string reserved to mean "no template".  I guess if you want to get fancy you could reserve all 1-4 byte strings.

**Comment by ekr** [comment]
Agreed. If you want to send a PR, I wouldn't object.
