### ISSUE TITLE
Figure out which transcript is authenticated

### ISSUE THREAD

**Issue by bemasc** [tlswg/draft-ietf-tls-ctls#57]
There was some discussion in the TLS session at IETF 113 about whether the Finished message should authenticate the reconstructed TLS transcript (as currently) or the cTLS transcript.  We should try to reach a conclusion about this.

Note that, if it is allowed to receive compression templates over an untrusted channel (#56), authenticating the cTLS transcript would presumably require including the compression template in the transcript, to avoid cross-template attacks (e.g. injecting the attacker's `key_share` without altering the transcript).  To avoid hashing JSON (which might be reformatted by intermediary systems), this would probably require defining a compact binary encoding of the JSON template (which I would like to have!).

**Comment by richsalz** [comment]
"compact binary encoding" brings to mind CBOR.  I think having a canonical/compat JSON format is beyond the scope of this doc.

**Comment by bemasc** [comment]
CBOR is a possibility, but defining a compact, canonical CBOR representation might also be nontrivial.  Personally, I would reuse the TLS extensions field format, with numeric key IDs and binary formats defined for each cTLS template element.

**Comment by richsalz** [comment]
Perhaps reading RFC 8949 will change your mind.

**Comment by bemasc** [comment]
My main concern about a generic JSON->CBOR conversion is that it is still an inefficient encoding, and I would like to be able to distribute cTLS profiles efficiently.  A generic CBOR encoding would still have keys represented as strings, binary values represented in hexadecimal, etc.

Even apart from efficiency, I still have concerns regarding canonicalization.  For example, some JSON-handling intermediaries are likely to alter the order of keys in maps, convert integer-valued floats to integers, etc.

**Comment by richsalz** [comment]
I was suggesting cbor as the inter-machine transport. As for keys-as-string, well, you *are* using json and therefore don't have alternatives.

Maybe use the TLS presentation language.  It's already part of TLS stacks, is pretty compact, and canonical.

**Comment by bemasc** [comment]
I have the impression that the preference is to move to a non-reconstruction handshake.  I've written up a PR that implements that: #60.  Unsurprisingly, this is a massive change to the document.

#60 includes the changes from the other two outstanding PRs, so they should be merged first.
