### ISSUE TITLE
Example Exchange missing CTLSCiphertext, PSK, and signature encoding

### ISSUE THREAD

**Issue by emanjon** [tlswg/draft-ietf-tls-ctls#83]
CTLSClientPlaintext and CTLSServerPlaintext seem to be included in the example exchange but CTLSCiphertext seems to be missing. My understanding is that ServerFlight and ClientFlight are sent over CTLSCiphertext which would add a mimimum of 2 * 11 bytes.

It is not explained why the signature is 64 bytes. In TLS 1.3, my understanding is that ecdsa_secp256r1_sha256 is variable length 12-76 bytes with an average length close to 75 bytes. Changing ecdsa_secp256r1_sha256 to ed25519 (or ecdsa_secp256r1_sha256_compact) would make it 64 bytes.

The introduction promises an example PSK handshake, but that is missing.

**Comment by bemasc** [comment]
@emanjon Please review #84, which attempts to fix the example as you've described.
